INFO [2019-10-22 11:50:02] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16884 10072 
 	 返回报文:{'id': '20191022115002001'} 

INFO [2019-10-22 11:50:02] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16884 10072 
 	 [SsoAPIView : get]Training complete in 0.071362 real seconds 

INFO [2019-10-22 11:50:04] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16884 4232 
 	 返回报文:{'id': '20191022115004001'} 

INFO [2019-10-22 11:50:04] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16884 4232 
 	 [SsoAPIView : get]Training complete in 0.000971 real seconds 

ERROR [2019-10-22 14:57:23] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 5016 2800 
 	 [SsoAPIView : auth  ] : [token已失效!];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 50 in wrapper
response=self.__run(func,outside_self,request,*args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 26 in __run
res = func(outside_self, request, *args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\app\sso\api.py line: 46 in auth
raise PubErrorCustom("token已失效!")
 

ERROR [2019-10-22 16:12:24] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 1804 12196 
 	 [SsoAPIView : auth  ] : [token已失效!];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 90 in wrapper
response=self.__run(func,outside_self,request,*args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 56 in __run
res = func(outside_self, request, *args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\app\sso\api.py line: 73 in auth
raise PubErrorCustom("token已失效!")
 

ERROR [2019-10-22 21:07:32] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 19788 18464 
 	 [SsoAPIView : login  ] : [请求报文有误!];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 89 in wrapper
kwargs=self.__request_validate(request,**kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 41 in __request_validate
raise PubErrorCustom("请求报文有误!")
 

ERROR [2019-10-22 21:10:22] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 19788 19328 
 	 [SsoAPIView : login  ] : [请求格式有误!];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 89 in wrapper
kwargs=self.__request_validate(request,**kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 44 in __request_validate
request.data_format = json.loads(decrypt(request.data.get('data')))
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\passwd.py line: 20 in decrypt
raise PubErrorCustom("请求格式有误!")
 

ERROR [2019-10-22 21:12:12] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 20368 6720 
 	 [SsoAPIView : login  ] : [账号不存在!];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 90 in wrapper
response=self.__run(func,outside_self,request,*args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 54 in __run
res = func(outside_self, request, *args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\app\sso\api.py line: 45 in login
raise PubErrorCustom("账号不存在!")
 

ERROR [2019-10-22 21:13:22] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 19888 21640 
 	 [SsoAPIView : login  ] : [Object of type Role is not JSON serializable];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 90 in wrapper
response=self.__run(func,outside_self,request,*args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 54 in __run
res = func(outside_self, request, *args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\app\sso\api.py line: 59 in login
RedisTokenHandler(key=token).redis_dict_set(res)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\db.py line: 13 in redis_dict_set
self.redis_client.set(self.key,json.dumps(value))
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\json\__init__.py line: 231 in dumps
return _default_encoder.encode(obj)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\json\encoder.py line: 199 in encode
chunks = self.iterencode(o, _one_shot=True)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\json\encoder.py line: 257 in iterencode
return _iterencode(o, 0)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\json\encoder.py line: 179 in default
raise TypeError(f'Object of type {o.__class__.__name__} '
 

ERROR [2019-10-22 21:16:08] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 31 error 16512 2044 
 	 [SsoAPIView : login  ] : [(1146, "Table 'shop.login' doesn't exist")];C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 90 in wrapper
response=self.__run(func,outside_self,request,*args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\core\decorator\response.py line: 54 in __run
res = func(outside_self, request, *args, **kwargs)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\app\sso\api.py line: 64 in login
"user_agent": request.META.get('HTTP_USER_AGENT')
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\manager.py line: 82 in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\query.py line: 417 in create
obj.save(force_insert=True, using=self.db)
;C:\Users\gigahertz\Desktop\Shop\Server\Sso\app\sso\models.py line: 17 in save
return super(Login, self).save(*args, **kwargs)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\base.py line: 729 in save
force_update=force_update, update_fields=update_fields)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\base.py line: 759 in save_base
updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\base.py line: 842 in _save_table
result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\base.py line: 880 in _do_insert
using=using, raw=raw)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\manager.py line: 82 in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\query.py line: 1125 in _insert
return query.get_compiler(using=using).execute_sql(return_id)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\compiler.py line: 1285 in execute_sql
cursor.execute(sql, params)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\utils.py line: 100 in execute
return super().execute(sql, params)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\utils.py line: 68 in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\utils.py line: 77 in _execute_with_wrappers
return executor(sql, params, many, context)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\utils.py line: 85 in _execute
return self.cursor.execute(sql, params)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\utils.py line: 89 in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\utils.py line: 85 in _execute
return self.cursor.execute(sql, params)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\backends\mysql\base.py line: 71 in execute
return self.cursor.execute(query, args)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\MySQLdb\cursors.py line: 206 in execute
res = self._query(query)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\MySQLdb\cursors.py line: 312 in _query
db.query(q)
;C:\Users\gigahertz\AppData\Local\Programs\Python\Python37\lib\site-packages\MySQLdb\connections.py line: 224 in query
_mysql.connection.query(self, query)
 

INFO [2019-10-22 21:17:33] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 10208 
 	 返回报文:{'token': 'f1c07fd850a84514647edc021fd854c381aaa00fcccc689ae87c7fc2260843a2e12a5dd9c90d84a0c9b03a06a8856ff3f01efdece79d9dc129ca107d62260c0a6f19dff05b8926314b787eb913a12326'} 

INFO [2019-10-22 21:17:33] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 10208 
 	 [SsoAPIView : login]Training complete in 0.034167 real seconds 

INFO [2019-10-22 21:18:36] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 18512 
 	 返回报文:{'token': 'd6981d789bc1ce33442e64bb1a3217d5ae36161825f65c05f6adef5e83756b733bc7a3a91b5d4c5c14e8a7789b5b9ed9477bce2270764aa31f21d3741311de617886ad64383c833045f9316c1da268f5'} 

INFO [2019-10-22 21:18:36] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 18512 
 	 [SsoAPIView : login]Training complete in 0.060845 real seconds 

INFO [2019-10-22 21:18:50] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 19412 
 	 返回报文:{'token': 'd7255aeeaf216669935ecd6e6cffc1de7318a7bf112fbcc7f0e8c008066f1ee4878241208bb076e16d936948c7ba3e7d37d1fe42d80f7bc3c7b319fab1bac73dfdbad91fdf9278213af8758b14292a28'} 

INFO [2019-10-22 21:18:50] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 19412 
 	 [SsoAPIView : login]Training complete in 0.028920 real seconds 

INFO [2019-10-22 21:18:58] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 6608 
 	 返回报文:{'token': 'f6ba23602e641bf1e8a9b9061448a773c759898d51c2a29afed97f8eed56c80911d969d83f1850bb3756b56445c5eb69cb94eee92d3bf4e366300b70c5b1e0d46684088d8f3f9fd9d3bb87279f3d4296'} 

INFO [2019-10-22 21:18:58] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 16512 6608 
 	 [SsoAPIView : login]Training complete in 0.030918 real seconds 

INFO [2019-10-22 21:36:27] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 18484 21084 
 	 返回报文:{'token': '212135302cb6d0e760cb44f694f7a24081634023e7d611c50a9680e4d3c78a15d52ca6ed317154dfb5a226f067e26c7ead42ca9a31cec626200ff07f1af0cc68d3dbfab7d1b785b972cd9aaf3b44fe9a'} 

INFO [2019-10-22 21:36:27] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 18484 21084 
 	 [SsoAPIView : login]Training complete in 0.278288 real seconds 

INFO [2019-10-22 21:38:26] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 19376 18704 
 	 返回报文:b'POu8JEQDaJOe7NaedL5qPXhm+jjjvlrGMljwLKQG6clhP+wikzKloARbvrxGB9lWk3s3XBvpd6YS7ISk1pzd4Vfg1xu17OYByFplXzZ3evzO4dhWSR18YdO5AJTLEuvlzYWKhljlNY5qXdp5Mrh2Ip0SwSqF8pXR1DLxIf9ru0eaBv/+0CHPvCWhFJkwGANKJ7bgNvpV4p9af0ScAcARFJDuegvxNyhMPj2FazMSuzE=' 

INFO [2019-10-22 21:38:26] C:\Users\gigahertz\Desktop\Shop\Server\Sso\lib\utils\log.py 38 info 19376 18704 
 	 [SsoAPIView : login]Training complete in 0.133659 real seconds 

